dcmh

diff --git a/.github/workflows/pipelineIC.yml b/.github/workflows/pipelineIC.yml
--- a/.github/workflows/pipelineIC.yml
+++ b/.github/workflows/pipelineIC.yml
@@ -86,59 +86,59 @@ jobs:
 
         #   steps:
 
-            - name: Run OWASP Dependency-Check JSON
-              uses: dependency-check/Dependency-Check_Action@main
-              with:
-                project: 'labfinal'
-                path: '.'
-                format: 'JSON'
-                out: 'dependency-check-report'
-                args: '--failOnCVSS 20' 
+            # - name: Run OWASP Dependency-Check JSON
+            #   uses: dependency-check/Dependency-Check_Action@main
+            #   with:
+            #     project: 'labfinal'
+            #     path: '.'
+            #     format: 'JSON'
+            #     out: 'dependency-check-report'
+            #     args: '--failOnCVSS 20' 
           
-            - name: Show Key Information from JSON Report
-              run: |
-                  REPORT="dependency-check-report/dependency-check-report.json"
+            # - name: Show Key Information from JSON Report
+            #   run: |
+            #       REPORT="dependency-check-report/dependency-check-report.json"
               
-                  if [ ! -f "$REPORT" ]; then
-                    echo "No se encuentra el reporte $REPORT"
-                    exit 1
-                  fi
+            #       if [ ! -f "$REPORT" ]; then
+            #         echo "No se encuentra el reporte $REPORT"
+            #         exit 1
+            #       fi
               
-                  echo "Vulnerabilidades encontradas:"
-                  jq '.dependencies[] | {file: .fileName, vulnerabilities: .vulnerabilities}' "$REPORT"
+            #       echo "Vulnerabilidades encontradas:"
+            #       jq '.dependencies[] | {file: .fileName, vulnerabilities: .vulnerabilities}' "$REPORT"
                 
-            - name: Analisis dependency check
-              run: |
+            # - name: Analisis dependency check
+            #   run: |
                         
-                        REPORT="dependency-check-report/dependency-check-report.json"
+            #             REPORT="dependency-check-report/dependency-check-report.json"
                     
                         
-                        ISSUES=$(jq '[.dependencies[].vulnerabilities[] | select(.cvssScore >= 4 and .cvssScore <= 10)] | length' "$REPORT")
+            #             ISSUES=$(jq '[.dependencies[].vulnerabilities[] | select(.cvssScore >= 4 and .cvssScore <= 10)] | length' "$REPORT")
                     
                        
-                        if [ "$ISSUES" -gt 0 ]; then
-                          echo "Se encuentran $ISSUES vulnerabilidades con CVSS entre 4 y 10."
-                          exit 1
-                        else
-                          echo "No se encuentra vulnerabilidades media-alta."
-                        fi
-            - name: Subir informe (JSON)
-              uses: actions/upload-artifact@v3
-              with:
-                          name: dependency-check-report-json
-                          path: dependency-check-report/dependency-check-report.json
-            - name: Summarize Vulnerabilities from JSON Report
-              run: |
-                            REPORT="dependency-check-report/dependency-check-report.json"
+            #             if [ "$ISSUES" -gt 0 ]; then
+            #               echo "Se encuentran $ISSUES vulnerabilidades con CVSS entre 4 y 10."
+            #               exit 1
+            #             else
+            #               echo "No se encuentra vulnerabilidades media-alta."
+            #             fi
+            # - name: Subir informe (JSON)
+            #   uses: actions/upload-artifact@v3
+            #   with:
+            #               name: dependency-check-report-json
+            #               path: dependency-check-report/dependency-check-report.json
+            # - name: Summarize Vulnerabilities from JSON Report
+            #   run: |
+            #                 REPORT="dependency-check-report/dependency-check-report.json"
                         
-                            if [ ! -f "$REPORT" ]; then
-                              echo "No se encuentra el reporte $REPORT"
-                              exit 1
-                            fi
+            #                 if [ ! -f "$REPORT" ]; then
+            #                   echo "No se encuentra el reporte $REPORT"
+            #                   exit 1
+            #                 fi
                         
-                            echo "Resumen de vulnerabilidades:"
-                            jq -r '.dependencies[] | select(.vulnerabilities != null) | 
-                              "\(.fileName): \(.vulnerabilities[]?.name) (\(.vulnerabilities[]?.severity))"' "$REPORT"
+            #                 echo "Resumen de vulnerabilidades:"
+            #                 jq -r '.dependencies[] | select(.vulnerabilities != null) | 
+            #                   "\(.fileName): \(.vulnerabilities[]?.name) (\(.vulnerabilities[]?.severity))"' "$REPORT"
 
 
 
@@ -151,7 +151,43 @@ jobs:
                             path: '.'
                             format: 'HTML'
                             out: 'dependency-check-report'
-                            args: '--failOnCVSS 20' 
+                            args: '--failOnCVSS 0'
+                           
+            - name: Analizar el informe HTML de Dependency-Check por severidad
+              run: |
+                              REPORT="dependency-check-report/dependency-check-report.html"
+                    
+                              # Verificar si el informe HTML fue generado
+                              if [ ! -f "$REPORT" ]; then
+                                echo "¡No se encontró el informe HTML de Dependency-Check!"
+                                exit 1
+                              fi
+                    
+                              echo "Buscando vulnerabilidades con severidad Media y Alta en el informe HTML..."
+                    
+                              # Contar vulnerabilidades con severidad Media
+                              MEDIUM_ISSUES=$(grep -o "Medium" "$REPORT" | wc -l)
+                    
+                              # Contar vulnerabilidades con severidad Alta
+                              HIGH_ISSUES=$(grep -o "High" "$REPORT" | wc -l)
+                    
+                              # Sumar el total de vulnerabilidades encontradas
+                              TOTAL_ISSUES=$((MEDIUM_ISSUES + HIGH_ISSUES))
+                    
+                              echo "Se encontraron $MEDIUM_ISSUES vulnerabilidades con severidad Media."
+                              echo "Se encontraron $HIGH_ISSUES vulnerabilidades con severidad Alta."
+                    
+                              # Fallar el pipeline si se encuentran vulnerabilidades con severidad Media o Alta
+                              if [ "$TOTAL_ISSUES" -gt 0 ]; then
+                                echo "Pipeline fallido: Se encontraron $TOTAL_ISSUES vulnerabilidades con severidad Media o Alta."
+                                exit 1
+                              else
+                                echo "No se encontraron vulnerabilidades con severidad Media o Alta."
+                              fi
+                            
+
+
+
           #  ###### art     
             - name: Upload Dependency-Check Report
               uses: actions/upload-artifact@v3
